### ISSUE TITLE
Panic within `scrape` 

### ISSUE THREAD

**Issue by jlcs-es** [bohdan-s/SungrowInverter#2]
## Description

I don't really know when or how many times `scrape` is called from `Sungather`, but this happens randomly, so the process works for some amount of time and then panics.

## Temporal patch

Use docker's `--restart unless-stopped` to restart the server.

## Sungather info

Docker image in Raspberry 3 of Sungather version v0.5.0

```
$ docker images
bohdans/sungather                       latest    1ff635fddfcd   2 months ago   466MB
```

```
Configuration	Value
host	192.168.y.yyy
port	502
timeout	10
retries	1
RetryOnEmpty	False
model	SH6.0RS
serial_number	yyyyyyyyyyy
level	3
scan_interval	30
use_local_time	False
smart_meter	True
connection	modbus
slave	1
start_time
```

## Logs

With `use_local_time: False`:

```
2023-03-18 12:18:50 WARNING  Failed to get Timestamp from Inverter, using Local Time: 2023-03-18 12:18:50
Failed to get Timestamp from Inverter, using Local Time: 2023-03-18 12:18:50
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/SungrowClient/SungrowClient.py", line 388, in scrape
    self.latest_scrape["year"],
    ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/sungather/sungather.py", line 190, in <module>
    main()
  File "/usr/src/sungather/sungather.py", line 154, in main
    success = inverter.scrape()
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/SungrowClient/SungrowClient.py", line 405, in scrape
    del self.latest_scrape["year"]
        ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'year'
```

With `use_local_time: True` same thing, different line:

```
Traceback (most recent call last):
  File "/usr/src/sungather/sungather.py", line 190, in <module>
    main()
  File "/usr/src/sungather/sungather.py", line 154, in main
    success = inverter.scrape()
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/SungrowClient/SungrowClient.py", line 379, in scrape
    del self.latest_scrape["year"]
        ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'year'
```

**Comment by bohdan-s** [comment]
Thank you, I know about this issue and a new build with a fix is coming :)

**Comment by vetinari** [comment]
should be fixed by #5
